version: "3.8"

services:
  tradex_app:
    build: .
    container_name: tradex_container
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"  # Dashboard
      - "5005:5005"  # Webhook
    #volumes:
      #- .:/app
      #- ./logs:/var/log
      #- ./logs:/app/logs
    command: /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
